# Generated by Django 4.2.1 on 2023-07-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprint',
            name='extraDeploys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='pointsMerged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='totalPoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
